### ISSUE TITLE
AOT branch

### ISSUE THREAD

**Issue by nampdn** [debben/ng2-admin#2]
Hi, I have try your branch of AOT and try to compile it in my local. But there is some problem with the ng compiler, could you please help me?
Here are error log:

Run `npm start` give this error:
```
TypeError: this.compiler.compileModules is not a function
    at CodeGenerator.codegen (C:\Users\iminar\Dev\angular\modules\@angular\compi                                                                                                                ler-cli\src\codegen.ts:71:26)
    at AotPlugin._make (C:\@Projects\@various\ng2-admin-aot\node_modules\@ngtool                                                                                                                s\webpack\src\plugin.js:186:43)
    at Compiler.<anonymous> (C:\@Projects\@various\ng2-admin-aot\node_modules\@n                                                                                                                gtools\webpack\src\plugin.js:151:75)
    at Compiler.applyPluginsParallel (C:\@Projects\@various\ng2-admin-aot\node_m                                                                                                                odules\tapable\lib\Tapable.js:156:14)
    at Compiler.<anonymous> (C:\@Projects\@various\ng2-admin-aot\node_modules\we                                                                                                                bpack\lib\Compiler.js:463:8)
    at Compiler.applyPluginsAsync (C:\@Projects\@various\ng2-admin-aot\node_modu                                                                                                                les\tapable\lib\Tapable.js:73:70)
    at Compiler.compile (C:\@Projects\@various\ng2-admin-aot\node_modules\webpac                                                                                                                k\lib\Compiler.js:456:7)
    at Watching.<anonymous> (C:\@Projects\@various\ng2-admin-aot\node_modules\we                                                                                                                bpack\lib\Compiler.js:46:17)
    at next (C:\@Projects\@various\ng2-admin-aot\node_modules\tapable\lib\Tapabl                                                                                                                e.js:81:11)
    at Compiler.invalidAsyncPlugin (C:\@Projects\@various\ng2-admin-aot\node_mod                                                                                                                ules\webpack-dev-middleware\middleware.js:119:3)
    at next (C:\@Projects\@various\ng2-admin-aot\node_modules\tapable\lib\Tapabl                                                                                                                e.js:83:14)
    at Compiler.<anonymous> (C:\@Projects\@various\ng2-admin-aot\node_modules\we                                                                                                                bpack\lib\CachePlugin.js:31:4)
    at next (C:\@Projects\@various\ng2-admin-aot\node_modules\tapable\lib\Tapabl                                                                                                                e.js:83:14)
    at Compiler.<anonymous> (C:\@Projects\@various\ng2-admin-aot\node_modules\aw                                                                                                                esome-typescript-loader\src\index.ts:215:13)
    at Compiler.applyPluginsAsync (C:\@Projects\@various\ng2-admin-aot\node_modu                                                                                                                les\tapable\lib\Tapable.js:85:13)
    at Watching._go (C:\@Projects\@various\ng2-admin-aot\node_modules\webpack\li                                                                                                                b\Compiler.js:44:16)
    at Watching.<anonymous> (C:\@Projects\@various\ng2-admin-aot\node_modules\we                                                                                                                bpack\lib\Compiler.js:36:8)
    at Compiler.readRecords (C:\@Projects\@various\ng2-admin-aot\node_modules\we                                                                                                                bpack\lib\Compiler.js:367:10)
    at new Watching (C:\@Projects\@various\ng2-admin-aot\node_modules\webpack\li                                                                                                                b\Compiler.js:33:16)
    at Compiler.watch (C:\@Projects\@various\ng2-admin-aot\node_modules\webpack\                                                                                                                lib\Compiler.js:204:17)
    at module.exports (C:\@Projects\@various\ng2-admin-aot\node_modules\webpack-                                                                                                                dev-middleware\middleware.js:146:27)
    at new Server (C:\@Projects\@various\ng2-admin-aot\node_modules\webpack-dev-                                                                                                                server\lib\Server.js:43:20)
```

Run `npm run build:prod` then `npm run server:prod`
It can load the index but have some trouble in:
```
Uncaught Error: Can't resolve all parameters for BaSlimScroll: (?).
    at CompileMetadataResolver.getDependenciesMetadata (http://localhost:8080/vendor.7339abac83e788a11088.bundle.js:26:30374)
    at CompileMetadataResolver.getTypeMetadata (http://localhost:8080/vendor.7339abac83e788a11088.bundle.js:26:27335)
    at CompileMetadataResolver.getDirectiveMetadata (http://localhost:8080/vendor.7339abac83e788a11088.bundle.js:26:16970)
    at http://localhost:8080/vendor.7339abac83e788a11088.bundle.js:26:19550
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:8080/vendor.7339abac83e788a11088.bundle.js:26:19175)
    at http://localhost:8080/vendor.7339abac83e788a11088.bundle.js:26:18759
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:8080/vendor.7339abac83e788a11088.bundle.js:26:17970)
    at RuntimeCompiler._compileComponents (http://localhost:8080/vendor.7339abac83e788a11088.bundle.js:36:27168)
```

**Comment by debben** [comment]
@nampdn ,

I've since updated the branch. I think what you were seeing was [this issue](https://github.com/angular/angular-cli/issues/2452). Upgrading the angular version to 2.1.2 seemed to fix it.

I've also got things just about working for AOT compilation. I've commented out just about everything in the branch except for the dashboard page. When running with `npm start`, the project will run in standard JIT mode.

To run in AOT, use `npm run build:prod`. This will compile the project in AOT mode and put the output in the dist folder. You can serve them locally with the command `node node_modules/.bin/http-server dist/`.

Right now the last major error is that there seems to be a different context being fed to webpack between the dev and prod configurations. For dev, things build fine. On prod, I have to change the loadChildren path in pages.routing.ts to be './pages/dashboard/dashboard.module#DashboardModule?sync=true'.

**Comment by nampdn** [comment]
Your work is awesome, I couldn't any branch from akveo to work with AOT compilation except yours. For the last major error, I hope it will be supported soon (in the mean time I will do like what you have to do).

**Comment by debben** [comment]
@nampdn ,

I've managed to resolve the last issue. A new version of angular2-router-loader allows the use of non-relative paths which will normalize according to the context the require is called from. I've pushed this change as a commit to the AOT branch.

**Comment by nampdn** [comment]
@debben Thanks you a lots. I'm going to try it now.
